/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef click_CONSTANTS_H
#define click_CONSTANTS_H

#include "click_types.h"

namespace thrift {

class clickConstants {
 public:
  clickConstants();

};

extern const clickConstants g_click_constants;

} // namespace

#endif
