/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "click_constants.h"

namespace thrift {

const clickConstants g_click_constants;

clickConstants::clickConstants() {
}

} // namespace

