import os, string
EnsureSConsVersion( 2, 3, 0 )


libs = [
    ":libjemalloc.so.1"
    ,"bolt"
    ,"mesos"
    ,":librocksdb.so.3.11.2"
    ,":libcityhash.so.0.0.0"
    ,"thriftnb"
    ,"thrift"
    ,"thriftz"
    ,":libboost_thread.so.1.55.0"
    ,":libboost_regex.so.1.55.0"
    ,":libfolly.so.31.0.0"
    ,":libglog.so.0.0.0"
    ,":libboost_program_options.so.1.55.0"
    ,":libboost_system.so.1.55.0"
    ,":libboost_filesystem.so.1.55.0"
    ,":libboost_date_time.so.1.55.0"
    ,":libboost_iostreams.so.1.55.0"
    ,":libevent-2.0.so.5.1.9"
    ,":libunwind.so.8.0.1"
    ,":libz.so.1.2.8"
    ,":libbz2.so.1.0.4"
    ,":liblz4.so.1.0.0"
    ,":liblzma.so.5.0.0"
    ,":libsnappy.so.1.1.4"
    ,":libdouble-conversion.so.1.0"
    ,":libcrypto.so.1.0.0"
    ,"rt"
    ,"pthread"
    ,":libarchive.so.13.1.2"
    ,":liblttng-ust.so.0.0.0"
    ,"dl"
]


cxxflags = [
    "-std=c++1y"
    ,"-Wall"
    ,"-Wnon-virtual-dtor"
    ,"-Werror"
    ,"-Wextra"
    ,"-Wformat"
    ,"-pedantic"
    ,"-Wmissing-braces"
    ,"-Wparentheses"
    ,"-ftemplate-depth-256"
    ,"-Woverloaded-virtual"
    ,"-Wpointer-arith"
    ,"-Wformat-security"
    ,"-Wunused"
    ,"-Wno-unused-parameter"
    ,"-Wcast-align"
    ,"-Wmissing-field-initializers"
    # ,"-flto" # TODO(agallego): enable later
]

cpp_defines = ["FOLLY_HAVE_PTHREAD_ATFORK"]
if int(ARGUMENTS.get("release",0)):
    print "Production mode"
    cxxflags = cxxflags + ["-O3"]
    cpp_defines.append("NDEBUG")
else:
    print "Debug mode"
    extraflags = ['-g3'
                  ,'-fno-omit-frame-pointer'
                  ,'-fvar-tracking-assignments'
                  ,'-gdwarf'
                  ,'-O1'
    ]
    cpp_defines.append("DEBUG")
    cxxflags = extraflags + cxxflags

env = Environment(ENV = os.environ
                  , CPPDEFINES = cpp_defines
                  , NUM_CPU = 4
                  , JOBS = 8
                  , CC = "gcc-4.9"
                  , CXX = "g++-4.9"
                  , CCFLAGS = " ".join(cxxflags)
                  , LD_LIBRARY_PATH="/lib:/usr/local/lib:/usr/lib:/usr/lib/x86_64-linux-gnu"
                  # , LINKFLAGS = ["-v"]
                  , LINKCOMSTR = "CONCORD...... linking... $TARGET"
)

# print env.Dump()

word_source = env.Program(target = "word_source",
                          source = Glob('word_source.cc'),
                          LIBS = libs,
                          CCFLAGS = ' '.join(cxxflags))

word_counter = env.Program(target = "word_counter",
                           source = Glob('word_counter.cc'),
                           LIBS = libs,
                           CCFLAGS = ' '.join(cxxflags))
