import os, string
EnsureSConsVersion( 2, 3, 0 )

libs = [
    "jemalloc"
    ,"bolt"
    ,"mesos"
    ,"rocksdb"
    ,"cityhash"
    ,"thriftnb"
    ,"thrift"
    ,"thriftz"
    ,":libboost_thread.so.1.55.0"
    ,":libboost_regex.so.1.55.0"
    ,"folly"
    ,"glog"
    ,":libboost_program_options.so.1.55.0"
    ,":libboost_system.so.1.55.0"
    ,":libboost_filesystem.so.1.55.0"
    ,":libboost_date_time.so.1.55.0"
    ,":libboost_iostreams.so.1.55.0"
    ,"event"
    ,"unwind"
    ,"z"
    ,"bz2"
    ,"lz4"
    ,"lzma"
    ,"snappy"
    ,"double-conversion"
    ,"crypto"
    ,"rt"
    ,"pthread"
    ,"archive"
]

cxxflags = [
    "-std=c++1y"
    ,"-fuse-ld=gold"
    ,"-Wall"
    ,"-Wnon-virtual-dtor"
    ,"-Werror"
    ,"-Wextra"
    ,"-Wformat"
    ,"-pedantic"
    ,"-Wmissing-braces"
    ,"-Wparentheses"
    ,"-ftemplate-depth-256"
    ,"-Woverloaded-virtual"
    ,"-Wpointer-arith"
    ,"-Wformat-security"
    ,"-Wunused"
    ,"-Wno-unused-parameter"
    ,"-Wcast-align"
    ,"-Wmissing-field-initializers"
    # ,"-flto" # TODO(agallego): enable later
]

cpp_defines = ["FOLLY_HAVE_PTHREAD_ATFORK"]
if int(ARGUMENTS.get("release",0)):
    print "Production mode"
    cxxflags = cxxflags + ["-O3"]
    cpp_defines.append("NDEBUG")
else:
    print "Debug mode"
    extraflags = ['-g3'
                  ,'-fno-omit-frame-pointer'
                  ,'-fvar-tracking-assignments'
                  ,'-gdwarf'
                  ,'-O1'
    ]
    cpp_defines.append("DEBUG")
    cxxflags = extraflags + cxxflags

env = Environment(ENV = os.environ
                  , CPPDEFINES = cpp_defines
                  , NUM_CPU = 4
                  , JOBS = 8
                  , CC = "gcc-5"
                  , CXX = "g++-5"
                  , CCFLAGS = " ".join(cxxflags)
                  , LINKFLAGS = ["-v"]
                  , LINKCOMSTR = "CONCORD...... linking... $TARGET"
)

word_source = env.Program(target = "word_source",
                          source = Glob('word_source.cc'),
                          LIBS = libs,
                          CCFLAGS = ' '.join(cxxflags))

word_counter = env.Program(target = "word_counter",
                           source = Glob('word_counter.cc'),
                           LIBS = libs,
                           CCFLAGS = ' '.join(cxxflags))
